FROM node:18-alpine3.16
WORKDIR /app
COPY ["package.json", "package-lock.json*", "./"]
RUN  yarn --force
RUN npm install -g serve
COPY . ./
RUN yarn web:build
RUN yarn api:load
EXPOSE 5173
EXPOSE 9001
CMD ["sh", "docker/start.sh"]
